version: "3.8"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   image: my-app-node:latest
  #   depends_on:
  #     - db
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - mynetwork
  #   volumes:
  #     - myappdata:/var/lib/myappnode/data
  #   environment:
  #     NODE_ENV: prod
  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  myappdata:
  dbdata:
